### ISSUE TITLE
RDS doesn't return all subdomain suffix variants when source pod lacks corresponding k8s service

### ISSUE THREAD

**Issue by ayj** [istio/pilot#683] opened 2017-05-08 04:55 UTC
#### Expectation:

RDS returns subdomain suffix variants so, for example, pods can use non-FQDN for services in the same namespace.

```
"service-one:80",
"service-one",
"service-one.default:80",
"service-one.default",
"service-one.default.svc:80",
"service-one.default.svc",
"service-one.default.svc.cluster:80",
"service-one.default.svc.cluster",
"service-one.default.svc.cluster.local:80",
"service-one.default.svc.cluster.local",
```
RDS returns expected destination route when querying pod has corresponding Kubernete service defined. When service is _not_ defined for client, RDS only returns routes with FQDN. 

#### Test files:
- [app.yaml](https://gist.github.com/bbfbc8b5448b058dc2c56e4a02dbc304)
- [add-service-two.yaml](https://gist.github.com/987d943c8586db540a8e2c098616b975)

#### Steps to reproduce:

 Deploy service-one (service+deployment) and service-two (deployment only)
```
$ kubectl apply -f app.yaml
$ istio-egress-4011202677-q114n  1/1       Running   0          3h        10.0.50.74   
istio-ingress-1282888920-r3477   1/1       Running   0          3h        10.0.50.73   
istio-manager-3064318764-kg8p3   2/2       Running   0          3h        10.0.51.79  
istio-mixer-2558274856-v9q6s     1/1       Running   0          3h        10.0.50.72   
service-one-3643458149-4dqrl     2/2       Running   0          7m        10.0.50.88   
service-two-3092497021-b5xb7     2/2       Running   0          7m        10.0.51.97   
```

Setup port forwarding to manager discovery pod. 
```
$ kubectl port-forward istio-manager-3064318764-kg8p3 8080
```

`service-two` query RDS and filter by routes to `service-one`.
```
$ curl -s localhost:8080/v1/routes/80/istio-proxy/10.0.51.97 | grep service-one
    "name": "service-one.default.svc.cluster.local|http",
     "service-one.default.svc.cluster.local:80",
     "service-one.default.svc.cluster.local",
```

Add service to service-two and verify expected subdomain suffix variants to service-one are now present.
```
$ kubectl apply -f add-service-two.yaml
$ curl -s localhost:8080/v1/routes/80/istio-proxy/10.0.51.97 | grep service-one
    "name": "service-one.default.svc.cluster.local|http",
     "service-one:80",
     "service-one",
     "service-one.default:80",
     "service-one.default",
     "service-one.default.svc:80",
     "service-one.default.svc",
     "service-one.default.svc.cluster:80",
     "service-one.default.svc.cluster",
     "service-one.default.svc.cluster.local:80",
     "service-one.default.svc.cluster.local",
```

**Comment by frankbu** [comment] 2017-05-08 18:19
That makes sense. It's working as designed. The short names have to be within the clients scope context, otherwise we would have all kinds of potential conflicts. Is this documented anywhere? It really needs to be.

**Comment by ayj** [comment] 2017-05-08 18:20
Shouldn't the common suffix be between the source _pod_ and target _service_?

**Comment by kyessenov** [comment] 2017-05-08 18:22
We're struggling to remove dependence on the kubernetes pods and namespaces. There is a notion of a "service instance" which is distinct from a pod. A pod can carry multiple service instances, just like a node can carry multiple pods.

**Comment by ayj** [comment] 2017-05-08 18:32
Wouldn't multiple service instances in the same pod always have the same suffix scope, e.g. namespace, cluster? 

What about things like batch/cron jobs? Require a dummy service to make Istio work?

**Comment by kyessenov** [comment] 2017-05-08 18:38
The question is how do you represent batch/cron jobs in a way that generalizes to raw VMs and cloudfoundry? The model is limited by design so we do not marry to kubernetes :) Currently, the batch job must use FQDN to access services. This is not terrible but inconvenient.

**Comment by ayj** [comment] 2017-05-08 18:53
Isn't this more an artifact of how we distribute configuration directly from the discovery service to envoy? The proxy agent, which will likely have platform aware parts anyway, could use k8s pod info augment the routes for common suffixes. That would give us greater control over proxy configuration distribution in general. 

Another alternate would be to make the discovery service platform aware which seems less desirable particularly when we need to support multiple-platforms in the same install. Keeping the platform awareness local to the proxy agent seems like a more reasonable compromise.

Or we push the problem to the user and create platform specific instructions.

**Comment by kyessenov** [comment] 2017-05-08 20:11
Routes are served through RDS, so this has to be solved by discovery services. The proxy identity has to provide the context somehow. Maybe resolve proxy IP to namespace and go from there?

**Comment by kyessenov** [comment] 2017-05-19 23:36
caused by #795 , would be a breaking change likely

**Comment by kyessenov** [comment] 2017-08-15 05:02
Fixed by https://github.com/istio/pilot/pull/1019

**Closed by kyessenov** 2017-08-15 05:02 UTC
Labels: bug, enhancement, platform/kubernetes, UX (User)
