### ISSUE TITLE
Envoy returning error while rules are updating

### ISSUE THREAD

**Issue by frankbu** [istio/pilot#1325] opened 2017-09-20 17:15 UTC
There seems to be a problem while route rule changes are propagating.

For example, after setting the default routes for the bookinfo services according to the request routing task (https://istio.io/docs/tasks/request-routing.html)

```
istioctl create -f samples/apps/bookinfo/rules/route-rule-all-v1.yaml
```

For several seconds the reviews and ratings services appear to not be returning the 200. Eventually the v1 versions do appear, but until then, the UI looks like this:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/2752495/30657015-17c2f46e-9e04-11e7-908c-c7b5caba1a1a.png">

**Comment by kyessenov** [comment] 2017-09-20 17:18
@rshriram changed the update interval to 30s. If routes, clusters, and endpoints are out of sync, some things may be unavailable at use-time.

**Comment by kyessenov** [comment] 2017-09-20 17:19
Logically, the updates should proceed in a sequence - EDS, CDS, RDS, and then LDS. I think Envoy does the right thing for first three, but not for LDS -> RDS usages. That means listeners are applied might be applied even when routes are not available.

**Comment by maruina** [comment] 2017-09-20 18:03
Can it be a duplicate of [pilot/926](https://github.com/istio/pilot/issues/926)?

**Comment by mandarjog** [comment] 2017-09-26 18:37
@rshriram @frankbu @kyessenov  @ijsnellf This issue was discussed at the standup today.
It is very important for 0.2 because it breaks a basic use case, however since the proper fix is very involved, we are going to document a work around.

1. Reduce the `drainDuration` to 2sec. This reduces the probability of the user seeing a 404.
2. Add an entry in the FAQ about this issue. Also state that for performance testing the `drainDuration` should be 30 sec or more.

**Comment by linsun** [comment] 2017-09-27 02:42
Is this covered by https://github.com/istio/istio/pull/958?

**Comment by mandarjog** [comment] 2017-09-27 20:55
@linsun it is covered there.
@ldemailly cc: for the 404 issue.

**Comment by rshriram** [comment] 2017-09-29 16:12
has been fixed by changing defaults back to 1s temporarily. Long term fix is to move to v2 API and that is a separate issue.

**Closed by rshriram** 2017-09-29 16:12 UTC
Labels: bug

**Comment by ldemailly** [comment] 2017-10-06 17:38
I have a repro in #1041
