### ISSUE TITLE
bin/e2e.sh initializer fails

### ISSUE THREAD

**Issue by ijsnellf** [istio/pilot#1101] opened 2017-08-24 18:56 UTC
`bin/e2e.sh` fails on the initializer creation step in Minikube.

Environment:
```
isaiah@xerxes:~$ minikube version
minikube version: v0.21.0
isaiah@xerxes:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"dirty", BuildDate:"2017-08-11T10:05:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Run `bin/e2e.sh`:
```
...
configmap "istio" created
Error from server (NotFound): error when deleting "STDIN": serviceaccounts "istio-sidecar-initializer-service-account" not found
Error from server (NotFound): error when stopping "STDIN": deployments.extensions "istio-sidecar-initializer" not found
I0824 13:12:07.211553   23956 infra.go:127] Sidecar initializer could not be deleted: exit status 1
serviceaccount "istio-sidecar-initializer-service-account" created
The Deployment "istio-sidecar-initializer" is invalid: metadata.initializers.pending: Invalid value: "null": must be non-empty when result is not set
E0824 13:12:07.461772   23956 driver.go:158] 

=================== Failed infrastructure tests! =====================
2 errors occurred:

* exit status 1
* exit status 1

ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

Related to this issue: https://github.com/kubernetes/kubernetes/issues/49048

Not seen in GKE.

**Comment by ayj** [comment] 2017-08-24 19:36
This error originates from [ValidateInitializers](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/validation/objectmeta.go#L204). It's not clear why this is failing in @ijsnellf's case but not on GKE. The recipe of explicitly setting the initializer field of the deployment to the empty list is recommend by k8s team (see [here](https://github.com/kubernetes/kubernetes/issues/49048#issuecomment-315889631)). 

@caesarxuchao, any ideas why bypassing the initializer via `pending: []` trick would be failing only in some cases with the error above? For reference our initializer deployment is [here](https://github.com/istio/pilot/blob/master/test/integration/testdata/initializer.yaml.tmpl#L14)

**Comment by caesarxuchao** [comment] 2017-08-24 20:13
>  It seems like it should always fail cased on ValidateInitializer code. For reference our initializer deployment is here

This code runs before the validation: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/initialization/initialization.go#L157-L159

What's the operation in the failed test? An Update will fail with that error message.

**Comment by ayj** [comment] 2017-08-24 21:21
Ah, it looks like that code run may not run if initializers alpha feature is not enabled via feature [flags](https://kubernetes.io/docs/admin/extensible-admission-controllers/#enable-initializers-alpha-feature).

@ijsnellf, are you testing with alpha features enabled in minikube? If not, can you try starting minikube with `--feature-gates=AllAlpha=true` (see [configuring_kubernetes.md](https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md))

The initializer deployment is being created (via `kubectl apply`).

**Comment by ayj** [comment] 2017-08-25 16:46
Here are minimal steps to reproduce with minikube v0.21.0 and [kubernetes-initializer-tutorial](https://github.com/kelseyhightower/kubernetes-initializer-tutorial). These do not depend on any Istio components.

```bash
minikube start --feature-gates=AllAlpha=true --kubernetes-version=v1.7.3
kubectl apply -f https://raw.githubusercontent.com/kelseyhightower/kubernetes-initializer-tutorial/master/configmaps/envoy-initializer.yaml
kubectl apply -f https://raw.githubusercontent.com/kelseyhightower/kubernetes-initializer-tutorial/master/deployments/envoy-initializer.yaml
```

**Comment by caesarxuchao** [comment] 2017-08-25 17:52
@ayj so the intializer admission plugin is enabled, and the problem is still there?

**Comment by ayj** [comment] 2017-08-25 18:15
yes, assuming `--feature-fates=AllAlpha=true` per https://kubernetes.io/docs/admin/extensible-admission-controllers/#enable-initializers-alpha-feature. InitializerConfiguration is present in the apiserver (see below). Is it possible minikube is using `--runtime-config=admissionregistration.k8s.io/v1alpha1` but forgot `--admission-control` flag? 

```json
$ curl localhost:8002/apis/admissionregistration.k8s.io/v1alpha1/
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "admissionregistration.k8s.io/v1alpha1",
  "resources": [
    {
      "name": "externaladmissionhookconfigurations",
      "singularName": "",
      "namespaced": false,
      "kind": "ExternalAdmissionHookConfiguration",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ]
    },
    {
      "name": "initializerconfigurations",
      "singularName": "",
      "namespaced": false,
      "kind": "InitializerConfiguration",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ]
    }
  ]
}
```

**Comment by ayj** [comment] 2017-08-25 19:31
Looks like the `Initializers` plugin was missing. The following works as expected.

```
minikube start \
    --extra-config=apiserver.Admission.PluginNames="NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,Initializers" \
    --feature-gates=AllAlpha=true \
    --kubernetes-version=v1.7.
```

**Comment by ayj** [comment] 2017-08-25 20:23
Minikube enables all API default with `--runtime-config=api/all` (see [minikube/cmd/localkube/cmd/options.go](https://github.com/kubernetes/minikube/blob/f5e73b08ba64792b9effe44cd21c228a2080353f/cmd/localkube/cmd/options.go#L46)). This is why `/apis/admissionregistration.k8s.io/v1alpha1/` showed up. `--feature-gates=AllAlpha=true` seems to only enables features defined by [kubernetes/blob/master/pkg/features/kube_features.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L24). 

For Istio 0.2 on Minikube we'll need to instruct users to manually add  `Initializers` and `GenericAdmissionWebhook` to the admission plugin list.

**Comment by ayj** [comment] 2017-08-28 21:27
This is a documentation concerning cluster initialization. https://github.com/istio/pilot/issues/1046 is tracking the general issue of documenting the initializer usage. Closing this bug.

**Closed by ayj** 2017-08-28 21:27 UTC
Labels: bug, e2e & integration
