### ISSUE TITLE
Pilot e2e seems to be 100% flaky for some unrelated PRs - proto caching or similar apparent issue

### ISSUE THREAD

**Issue by ldemailly** [istio/pilot#1112] opened 2017-08-27 20:39 UTC
https://github.com/istio/pilot/pull/1102

**Comment by ldemailly** [comment] 2017-08-27 20:44
follow up on https://github.com/istio/istio/issues/537

**Comment by sebastienvas** [comment] 2017-08-27 21:36
PLease backup your complaint with data:
https://prow.istio.io/?job=istio-presubmit, I don't see any failure here.

**Comment by ldemailly** [comment] 2017-08-27 21:55
please assume if someone bothers filing an issue maybe it's worth looking into it instead of closing it without looking. if you followed the link in the description:

https://k8s-gubernator.appspot.com/pr/istio/pilot/1102

<img width="765" alt="screen shot 2017-08-27 at 2 50 50 pm" src="https://user-images.githubusercontent.com/3664595/29754326-85f7b364-8b37-11e7-89d6-fa9d2b282a3c.png">

is that enough red ? and it's not the only pr that I noticed with the same issue
and again this is pilot not istio

**Comment by sebastienvas** [comment] 2017-08-27 22:45
Please provide actual action items, as this kind of random bugs can remain open forever. Please qualify which part of the presubmit is failing such that people can understand where a change is needed and don't blindly assign to people.

Assigning to @kyessenov  as this pilot e2e.

**Comment by sebastienvas** [comment] 2017-08-27 22:49
https://prow.istio.io/?job=pilot-presubmit for history of the last jobs.

**Comment by rshriram** [comment] 2017-08-28 13:00
According to logs, the gRPC echoservice API does not exist. I don't understand why. I changed the proto and renamed it to GRPCEchoService. I was hoping that there was some bazel magic to auto generate pb.go files. FWIW, my pr passed. And so did a subsequent pr from zijun.

**Comment by ldemailly** [comment] 2017-08-28 19:36
seems to be 100% on the #1102 PR

**Comment by sebastienvas** [comment] 2017-08-28 20:09
@kyessenov I am not sure I understand why this is happening. I had suspicion that bazel cache could be the cause of this, so I cleared it, but this issue is still happening.

**Comment by kyessenov** [comment] 2017-08-28 20:52
Clearly, it's bazel caching. Did you clear all output groups in bazel? We're using static output group for docker images.

**Comment by sebastienvas** [comment] 2017-08-28 21:13
I remove the entire directory.

**Comment by ldemailly** [comment] 2017-08-28 22:49
could it be a deployment issue ? (the old version is still the one deployed, maybe related to pull policy if somehow tags aren't updated?)

**Comment by ldemailly** [comment] 2017-08-29 02:06
it appears almost like we're not testing what we build or some such - off by 1 image issue ?

**Comment by sebastienvas** [comment] 2017-08-29 04:56
Can we do a rebase on that PR to confirm this ?

**Comment by sebastienvas** [comment] 2017-08-29 04:56
if we do a rebase, it will be a new sha and therefor a new image.

**Comment by ldemailly** [comment] 2017-08-29 06:53
the pr finally passed after the revert of the grpc/echo rename
we can probably recreate the issue in a branch to debug it

**Comment by sebastienvas** [comment] 2017-09-15 20:45
I am not sure how to fix this. I ll create a job that clear the bazel cache every week or something

**Comment by ldemailly** [comment] 2017-09-15 21:54
I think the oncall should repro the issue when time permits

**Comment by xiaolanz** [comment] 2017-09-18 16:17
No more flakiness is observced.

**Closed by xiaolanz** 2017-09-18 16:17 UTC
Labels: build & test infrastructure, flaky-test, internal-infra-bug, oncall

**Comment by ldemailly** [comment] 2017-09-18 16:57
I meant recreate a change of name pr and see it break other PRs
