### ISSUE TITLE
agent receiving new config in a loop

### ISSUE THREAD

**Issue by uday1bhanu** [istio/pilot#854] opened 2017-06-10 08:43 UTC
> $ istioctl version
> istioctl version:
> Version: 0.1.5
> GitRevision: 21f4cb4
> GitBranch: master
> User: jenkins@ubuntu-16-04-build-de3bbfab70500
> GolangVersion: go1.8.1
> KubeInjectHub: docker.io/istio
> KubeInjectTag: 0.1
> 
> 
> apiserver version:
> Version: 0.1.5
> GitRevision: 21f4cb4
> GitBranch: master
> User: jenkins@ubuntu-16-04-build-de3bbfab70500
> GolangVersion: go1.8.1

> $ minikube version
> minikube version: v0.19.0

> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-05-09T23:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

> $ cat /etc/redhat-release
> CentOS Linux release 7.2.1511 (Core)

> Kubernetes deployment file, and the service are in a separate file
> $ kubectl create -f <(istioctl kube-inject -f courses-deployment.yaml)
> $ kubectl create -f <(istioctl kube-inject -f courses-service.yaml)

Kubernetes deployment  of a containerized spring boot application works as expected, but when i use istioctl to generate the deployment config from my deployment config, the proxy side car container that istio configured is being restarted constantly. When i looked at the proxy container logs, I see that the agent receives the new config every ~20 secs and it increases the epoch and does this in loop forever and so its failing to come up. Below is the sample from the attached log file _**agent-epoch-loop.log**_ which has the complete log from the proxy container. 
**$ cat agent-epoch-loop.log | grep Received**
I0610 05:21:20.955447       1 agent.go:182] Received new config, resetting budget
I0610 05:21:22.219575       1 agent.go:182] Received new config, resetting budget
I0610 05:22:19.655475       1 agent.go:182] Received new config, resetting budget
I0610 05:22:48.847116       1 agent.go:182] Received new config, resetting budget
I0610 05:22:58.847580       1 agent.go:182] Received new config, resetting budget
_**< snip >**_

I have tried to capture the envoy config revisions that are generated for each epoch into separate files 
_**agent-epoch-${epoch-value}.log**_ When i diff the envoy configuration generated with the subsequent epoch and compare with the diff for the subsequent epochs i see a pattern. EX: diff epoch 1 with the 2(captured in _**diff-epoch-1-2.log**_), i see a change in the service name _"target.service": "" -> "target.service": "courses.default.svc.cluster.local"_ and bunch of additional differences, and diff epoch 2 with 3(captured in _**diff-epoch-2-3.log**_) I see that service name is reset to back to how it was in epoch 1 _"target.service": "courses.default.svc.cluster.local" -> "target.service": ""_

looks like epoch 1,3,5,7 all are identical(git diff agent-epoch-1.log agent-epoch-3.log is empty!)
and epoch 2,4,6,8 all are identical(git diff agent-epoch-2.log agent-epoch-4.log is empty)

I tried looking into the pilot agent code, but want able to figure it out why its recognizing a change in the configuration.

Attaching all the logs in the zip file.
[istio-agent-loop.zip](https://github.com/istio/pilot/files/1065687/istio-agent-loop.zip)

Any help is much appreciated!

**Comment by kyessenov** [comment] 2017-06-10 16:52
Thanks for report!

There's something wrong with the config/environment which causes envoy to segfault every time. I'll need to run envoy under gdb to pinpoint the failure. Alternatively, you could send us a coredump (files _core_ under _/tmp_). 

Regarding the config change, this is caused by Kubernetes marking the endpoint as unhealthy (since proxy does not pass through health probes on port 8081).  The 20 sec interval is probably how long Kubernetes waits to mark a dead endpoint. What's puzzling is why it keeps coming back alive.

You could try removing health probes for your deployments to see if that's causing proxy to crash.

**Comment by uday1bhanu** [comment] 2017-06-11 05:15
Thank you for looking into it.
Im attaching the core-dump logs.

I have tried removing the health checks, and now the proxy container stays and doesnt restart. 
[core-dump.tar.gz](https://github.com/istio/pilot/files/1066249/core-dump.tar.gz)

**Comment by lenalebt** [comment] 2017-08-14 15:48
I have a very similar problem. I also see envoy restarts, but they happen due to SIGTERM:

> August 14th 2017, 17:28:40.154 | proxy | I0814 15:28:40.154170       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> -- | -- | --
> 
>   | August 14th 2017, 17:28:40.155 | proxy | I0814 15:28:40.155199       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> 
>   | August 14th 2017, 17:28:40.156 | proxy | [2017-08-14 15:28:40.155][277][warning][main] terminating parent process
> 
>   | August 14th 2017, 17:28:40.156 | proxy | [2017-08-14 15:28:40.155][277][warning][main] shutting down admin due to child startup
> 
>   | August 14th 2017, 17:28:40.158 | proxy | I0814 15:28:40.158215       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> 
>   | August 14th 2017, 17:28:40.161 | proxy | I0814 15:28:40.160773       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> 
>   | August 14th 2017, 17:28:40.163 | proxy | I0814 15:28:40.163239       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> 
>   | August 14th 2017, 17:28:40.169 | proxy | I0814 15:28:40.163751       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> 
>   | August 14th 2017, 17:28:40.169 | proxy | I0814 15:28:40.169105       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> 
>   | August 14th 2017, 17:28:40.173 | proxy | I0814 15:28:40.172842       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> 
>   | August 14th 2017, 17:28:40.209 | proxy | I0814 15:28:40.209336       1 controller.go:152] Event update: key "default/caas-admin-webapp"
> 
>   | August 14th 2017, 17:28:40.330 | proxy | [2017-08-14 15:28:40.330][283][warning][main] starting main dispatch loop
> 
>   | August 14th 2017, 17:28:40.385 | discovery | W0814 15:28:40.385710       1 discovery.go:111] Overriding cached data for entry /v1/registration/istio-egress.default.svc.cluster.local
> 
>   | August 14th 2017, 17:28:40.598 | proxy | [2017-08-14 15:28:40.594][283][warning][main] all clusters initialized. initializing init manager
> 
>   | August 14th 2017, 17:28:40.621 | proxy | [2017-08-14 15:28:40.621][283][warning][main] all dependencies initialized. starting workers
> 
>   | August 14th 2017, 17:28:40.643 | proxy | [2017-08-14 15:28:40.642][277][warning][main] closing and draining listeners
> 
>   | August 14th 2017, 17:28:40.688 | discovery | W0814 15:28:40.687849       1 discovery.go:111] Overriding cached data for entry /v1/routes/80/istio-proxy/172.19.0.22
> 
>   | August 14th 2017, 17:28:40.893 | kube-events | last fetched $resource_version: 5601
> 
>   | August 14th 2017, 17:28:40.998 | proxy | [2017-08-14 15:28:40.997][258][warning][main] caught SIGTERM
> 
>   | August 14th 2017, 17:28:40.998 | proxy | [2017-08-14 15:28:40.997][258][warning][main] shutting down due to child request
> 
>   | August 14th 2017, 17:28:40.998 | proxy | [2017-08-14 15:28:40.997][264][warning][main] shutting down parent after drain
> 
>   | August 14th 2017, 17:28:40.998 | proxy | [2017-08-14 15:28:40.997][258][warning][main] main dispatch loop exited
> 
>   | August 14th 2017, 17:28:41.006 | proxy | [2017-08-14 15:28:41.005][258][warning][main] exiting
> 
>   | August 14th 2017, 17:28:41.010 | proxy | I0814 15:28:41.009413       1 agent.go:207] Epoch 40 exited normally
> 
>   | August 14th 2017, 17:28:41.084 | kube-events | last fetched $resource_version: 5603
> 
>   | August 14th 2017, 17:28:41.677 | proxy | W0814 15:28:41.676425       1 reflector.go:323] /home/jenkins/.cache/bazel/_bazel_jenkins/6edf10d6e3c910893d528f5032a4eb0d/bazel-sandbox/b8d5e676-c995-4096-a33f-355674ceaab6-429/execroot/pilot/bazel-out/local-fastbuild/bin/external/io_k8s_client_go/tools/cache/go_default_library.a.dir/k8s.io/client-go/external/io_k8s_client_go/tools/cache/reflector.go:96: watch of *kube.Config ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [4604/3163]) [5603]
> 
>   | August 14th 2017, 17:28:41.826 | proxy | I0814 15:28:41.826269       1 controller.go:152] Event update: key "default/caas-rest-api-455659607-kw0pg"
> 
>   | August 14th 2017, 17:28:41.840 | proxy | I0814 15:28:41.840367       1 controller.go:152] Event update: key "default/caas-rest-api-455659607-kw0pg"
> 
>   | August 14th 2017, 17:28:41.854 | proxy | I0814 15:28:41.853974       1 controller.go:152] Event update: key "default/caas-rest-api-455659607-kw0pg"

When I remove the readiness probes of the services, everything is working. I also discovered that the iptables rules in the underlying minikube keep changing all the time:

> Chain KUBE-SERVICES (2 references)
> target     prot opt source               destination         
> REJECT     tcp  --  anywhere             10.0.0.152           /* default/istio-pilot:http-apiserver has no endpoints */ tcp dpt:tproxy reject-with icmp-port-unreachable
> REJECT     tcp  --  anywhere             anywhere             /* default/firstspirit-server:http has no endpoints */ ADDRTYPE match dst-type LOCAL tcp dpt:32121 reject-with icmp-port-unreachable
> REJECT     tcp  --  anywhere             10.0.0.206           /* default/firstspirit-server:http has no endpoints */ tcp dpt:8000 reject-with icmp-port-unreachable
> REJECT     tcp  --  anywhere             anywhere             /* default/caas-rest-api:http-ext-to-delete has no endpoints */ ADDRTYPE match dst-type LOCAL tcp dpt:32031 reject-with icmp-port-unreachable

The rules appear and disappear.

These are my versions:

> $ istioctl version

> istioctl version:
> 
> Version: 0.1.6
> GitRevision: dab2033
> GitBranch: release-0.1
> User: jenkins@ubuntu-16-04-build-12ac793f80be71
> GolangVersion: go1.8.1
> KubeInjectHub: docker.io/istio
> KubeInjectTag: 0.1
> 
> 
> apiserver version:
> 
> Version: 0.1.6
> GitRevision: dab2033
> GitBranch: release-0.1
> User: jenkins@ubuntu-16-04-build-12ac793f80be71
> GolangVersion: go1.8.1

> $ minikube version
> minikube version: v0.21.0

> kubectl version
> Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

As I said, it's working without the readiness probes.

**Comment by kyessenov** [comment] 2017-08-14 18:53
Thank you for the report. This particular problem is likely due to non-determinism in the health probe config generation. We're rebuilding health check with the change to LDS config generation . We'll make sure that this will help reduce caching/restart problems.

**Comment by kyessenov** [comment] 2017-08-17 07:01
likely fixed by #1024

**Closed by kyessenov** 2017-08-17 07:01 UTC
Labels: bug
