### ISSUE TITLE
ConfigMap copy issue

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#1272] opened 2017-09-14 18:04 UTC
In 0.1.x series of Pilot, the proxy agent generated configuration for TCP, and needed access to the core startup configuration of pilot discovery service. This resulted in a shared configuration unit (a configmap) that was meant to stay in sync between the agent and the service, as inconsistencies would likely result in inability to communicate between sidecars.

In 0.2.x series of Pilot, the situation has improved as most of the configuration is now centrally generated in the service. The agent still requires small amount of settings (that have not yet been worked into xDS APIs). These settings are mostly static (e.g. drain durations, etc), and need not be changed for the duration of pod existence. The ideal situation is full elimination of these settings when xDS fully covers the entire surface of Envoy config. These settings are currently injected by kube-inject or initializer or CI/CD or human operator as startup-flags. There's simply no need to access Pilot service config from the agent directly.

Since the agent does not read the config map, there's no longer need to copy ConfigMap from installation namespace (where pilot resides) to application namespace (where agent resides). Remember that ConfigMaps are only visible within a single namespace. 

Currently, kube-inject copies the configmap over to the application namespace as part of injection process. I believe we should remove the copying bit since the produced configmap is not being consumed.

@rshriram @andraxylia @costinm @linsun @louiscryan @frankbu

**Comment by rshriram** [comment] 2017-09-14 18:26
I would like to add that this copying happens without user awareness, and that is a bad UX, IMO. Till date, Istio has been purely readonly in terms of reading info from kubernetes. It does not mutuate k8s state during runtime (istioctl is a different matter since its executed by the user). If I were to simply try the kube-inject command to see the resulting output, I would unwittingly create a config map if the namespace existed (or overwrite an existing map), or kube-inject will just fail if the namespace doesn't exist.

For example:
```shriram@shrirams-mbp:~/istio.io/istio $ cat < ./istioctl-osx -n test kube-inject --hub gcr.io/istio-testing -f samples/apps/bookinfo/bookinfo.yaml
Error: cannot create Istio configuration map in namespace test: namespaces "test" not found```

Here my intention was to not execute any commands in kubernetes. It was to just see the resulting output of kube-inject, as a user might be way of simply letting a tool inject arbitrary containers into their pods. 

Hedging on the initializer is not feasible since its still an alpha feature that not many clusters would enable.

**Comment by rshriram** [comment] 2017-09-14 18:28
cc @dcberg

**Comment by costinm** [comment] 2017-09-14 18:37
+1 on not copying the config map by default, if we can confirm that it is not used by any code running in the namespace.

**Comment by costinm** [comment] 2017-09-14 18:38
If we do find code using it - we can also have the kube-inject generate the config map if one doesn't exist.

However - in 0.3 it is very likely we'll need to make the config more flexible, so each namespace and service can override specific settings ( like mTLS ).

**Comment by costinm** [comment] 2017-09-14 18:41
Kuat - can you point to any doc on "ConfigMaps are only visible within a single namespace." ? My understanding was that if you have proper RBAC access, you can access (using k8s API) any config map.

It can't be mounted in a different namespace - but access is still possible, i.e. another option to istioctl copying the config map is to have pilot or some controller create the copy if needed.

**Comment by linsun** [comment] 2017-09-14 18:44
totally + 1 on not copying config map over on each used namespace by the user, especially if the config map isn't even used.   This needs to get in for 0.2.x as it impacts user's experience (1) i can't share my kube injected generated yaml with you to run it, 2) complicated the migration in the future 3) ugly user experience with copying config map failed error 4) create unneeded resources in user's namespace.

**Comment by linsun** [comment] 2017-09-14 18:46
@costinm you could assign permissions to allow configmaps to be accessible for multiple namespaces but that doesn't mean the user would want to do that.  Neither should we ask user to change their rbac config for namespace because of istio.

**Comment by rshriram** [comment] 2017-09-14 19:04
Having a single globally "readable" resource is the clean solution IMO.

**Comment by kyessenov** [comment] 2017-09-14 19:14
Here
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
"ConfigMaps reside in a specific namespace
<https://kubernetes.io/docs/user-guide/namespaces/>. A ConfigMap can only
be referenced by pods residing in the same namespace."

**Comment by andraxylia** [comment] 2017-09-14 20:44
If the config map is not used, how does the proxy know where to find istio services (pilot discovery, ingress, egress? 

Is here the assumption the change that starts envoy with more arguments will be accepted?

**Comment by andraxylia** [comment] 2017-09-14 20:50
@rshriram  kube-inject is not the proper way to solve this, this is why is marked as temporary
istio/pilot#1153 addresses this the proper way, in the context where config maps are maintained, and it is trivial to implement with the current design, with little risk for collateral damage. If config maps are not needed in all namespaces, so much better, we can close 1153.

**Comment by costinm** [comment] 2017-09-14 20:53
@linsun: I agree, that is exactly my point. User should not need RBAC permissions or access across namespaces - any config they change should be in their own namespace. 

If there is anything to configure - in ConfigMap or CRD - it should be local, in his own namespace.

If the config map is not used now - because we don't yet have ability to tune some features per namespace or per pod - it is ok to not copy it, and I 100% agree it shouldn't be a side-effect on istioctl.
But any config solution should be flexible enough to support namespace-local config overrides, pod/service overrides - with the istio-system settings only accessible to the cluster admin, not to individual namespace.

**Comment by costinm** [comment] 2017-09-14 20:56
@kyessenov - yes, that's my undestanding as well, ConfigMap can only be mounted in a pod ( or set as env ) in their current namespace.

CRDs don't have this problem - because AFAIK they can't be mounted or set as env in any namespace :-) 

But both CRD and ConfigMaps can be accessed programmatically from istio-system ( which has broad cluster permissions ), so we can apply a hierarchical config, where users don't need write access to istio-system.

**Comment by andraxylia** [comment] 2017-09-14 20:58
@linsun I disagree with the point users would not want to change the default. As an example, the transparent injection of proxy. User may decide to enable it for pods in a specific namespace, and disable it for other namespaces. Same with auth. cc @ayj 

We must avoid putting the carriage before the horse and start with some concrete use cases about what features can be enable/disabled and in what cases -the opt-in, opt-out mechanism. Then we can look at implementation details like this one, and decide if config maps are the way to implement the use case, or maybe we have other options. I feel this discussion got biased and we forgot to start with the beginning.

**Comment by rshriram** [comment] 2017-09-14 22:57
We should certainly support per namespace configs in future, but lets do it in a proper design process. Because, this is a big feature - it is unknown as to how a mTLS enabled namespace and non-mTLS enabled namespace interact/work, given that they all share a single Pilot. There is a bunch of work left there and this feature is completely new. And a non-mixer enabled service and mixer-enabled service interact. Also totally new. This is basically the same argument that @smawson and @costinm had, for dynamically turning on/off auth in the mesh. Fully untested and prone to errors/downtime.

This issue is about the side effects of silent config map creation, expectation that there will be config maps per namespace. Adding a controller to automatically create config maps will solve the problem partially, but we will now be adding an istio component that requires write access to the cluster - so far we just read. It is also something that I would be wary of. Just because I created a namespace does not mean something needs to be written to it. Our design has been largely elegant so far. This config writing controller seems like an inelegant way to percolate this globally readable info.

**Comment by costinm** [comment] 2017-09-14 23:10
We do support per namespace config in 0.1 (that's all we had) - so at most we have a regression if cluster-wide doesn't honor/use them anymore. I agree not all interactions are tested - and some settings ( like mTLS) clearly can't be yet fine-tuned. 

And I think we have consensus that silent map creation is a bug - the fix involves not mounting the config maps first, and I'm not sure what side effects this will have, i.e. it involves removing a feature we had, ability to inject config files. 

Keep in mind that changing sidecar configuration from a config file to flags was changed very recently, and it is not entirely clear it is a good change or we fully understand the consequences ( i.e. now a config change requires re-injecting all pods - while with the config it just required reloading them ). Since it's very clear in a patch release we'll need to bring finer-tuned config for pods and namespaces, and possibly ability to config additional data (for TLS) - I'm not entirely sure removing the mount is an improvement. 

The main reason for removing the mount of the config map is to not have to copy/create the config map - but I think the real problem is not the config map, but the way it is created as side-effect. And of course the lack of design on fine-grained config - which we plan to address in 0.3

**Comment by kyessenov** [comment] 2017-09-14 23:12
Costin I want to make two things clear:
1. Pilot agent is entirely different from 0.1 and 0.2. The whole xDS is a major architectural change.
2. We never claimed to support picking up updates from config maps. In fact, there is not a single use of config map here that listens on changes to config maps.

**Comment by kyessenov** [comment] 2017-09-14 23:27
Example of removing unnecessary mount with no effect: https://github.com/istio/istio/pull/815

**Comment by ldemailly** [comment] 2017-09-15 01:18
Sounds good to me. I think we need a single key/level of indirection, for the sidecar it's the pilot ip+port that manages it (which in turn can be smart and look at per namespace or per selector config, now or later)

For other config tbd in https://github.com/istio/istio/issues/632 in 0.3

**Comment by ldemailly** [comment] 2017-09-15 01:22
as mentioned in https://github.com/istio/pilot/issues/1153#issuecomment-326432403 14 days ago:

> for 0.3 I think we should have an api (or a client) that returns the config for a given caller with a map like
> ```
> namespace1:   istio-config1
> namespace2,namespace3: istio-config2
> namespace4: NO_ISTIO
> *: istio-config-default //default/fallback
> ```
> instead of relying on configMaps needing copying and sync
> 
> but for 0.2 whichever we can get done is great

**Comment by kyessenov** [comment] 2017-09-15 01:26
We can get quite fancy with how we customize each newly injected pod, but the question is then restricted to the injector itself, and does not touch pilot/discovery situation. The injector (kube-inject or admission controller) is free to manufacture either or a long list of flags or mount a file or whatnot, and all those options are transparent to the user. The injector can rely on information where pod resides or pod annotations to tune the settings. This is a great option, but that's not in 0.2 and the current "one-config-map-for-all" that is not used, is far from ideal.

**Comment by linsun** [comment] 2017-09-15 15:40
I think we are now moving decision to if we should enable users to configure the configuration at the namespace level.  That is definitely not a scenario interesting for us in 0.2 beta imho.  This is the release we are introducing cluster-wide Istio, we want to make it easy and not complicated where people will think the configuration is cluster-wide.   This configuration at individual namespace level feature could be introduced post 0.2 if there is user requirement after users have tried the cluster-wide Istio but there is no user requirement for that today.

**Comment by rshriram** [comment] 2017-09-15 16:32
To top what Lin said, every user email (if you happen to peruse them) asks
for "how do I make these rules work in other namespaces" ? Or goes
something like "rule does not work in another namespace". Not a single
person said, I would like to have namespace specific Istio. I encourage you
to peruse through the istio-users.

-- 

~shriram

**Closed** 2017-09-15 18:15 UTC

**Comment by dcberg** [comment] 2017-09-19 10:55
What was the resolution here? How will configs get shared within the cluster?
It was not clear if the ConfigMap was actually being used. If not then remove it (my 2 cents).

**Comment by linsun** [comment] 2017-09-19 13:10
@dcberg config maps are not used by the pilot agent so @kyessenov put code in #1276 to remove the copy of the config maps to each app's namespace.
